# -*- coding: utf-8 -*-
import os.path

# Form implementation generated from reading ui file 'weather.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 600)
        self.refresh = QtWidgets.QPushButton(Dialog)
        self.refresh.setGeometry(QtCore.QRect(590, 550, 75, 23))
        self.refresh.setObjectName("refresh")
        self.search = QtWidgets.QPushButton(Dialog)
        self.search.setGeometry(QtCore.QRect(680, 550, 75, 23))
        self.search.setObjectName("search")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 761, 511))
        self.groupBox.setObjectName("groupBox")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(70, 20, 81, 21))
        self.comboBox.setObjectName("comboBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 20, 54, 12))
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit.setGeometry(QtCore.QRect(30, 60, 701, 431))
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(Dialog)
        self.search.clicked.connect(Dialog.searchWeather) # type: ignore
        self.refresh.clicked.connect(Dialog.refresh) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.refresh.setText(_translate("Dialog", "刷新"))
        self.search.setText(_translate("Dialog", "查询"))
        self.groupBox.setTitle(_translate("Dialog", "天气预报"))
        self.add_city()
        self.label.setText(_translate("Dialog", "城市"))
        self.textEdit.setText("查一查天气怎么样？")

    def add_city(self):
        if os.path.exists("weather.json"):
            import json
            with open("weather.json", "r", encoding="utf-8") as f:
                data = json.load(f)
                index = 0
                for city in data:
                    if city["name"] == "乌鲁木齐":
                        index = data.index(city)
                        print("乌鲁木齐索引：{}".format(index))
                    self.comboBox.addItem(city["name"])
                print("乌鲁木齐索引：{}".format(index))
                self.comboBox.setCurrentIndex(index)
        else:
            print("weather.json not exist")
            self.comboBox.addItem("乌鲁木齐")
            self.comboBox.setCurrentIndex(0)
